#!/usr/bin/env node
/**
 * Regenerates bot/knowledge/10-site-facts.md from src/data/*.ts.
 *
 * The bot's facts and the site's pages come from one source, so adding a role
 * or a project updates both. Node 24 strips the types on import, which is why
 * this can read the .ts modules directly instead of regex-scraping them.
 *
 * Run:  npm run bot:context     (also runs as part of `npm run build`)
 *
 * Do not hand-edit the generated file — put the human context, the parts that
 * are not on the site, in 20-about.md instead.
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = (f) => join(here, '..', 'src', 'data', f);

const { site, nav } = await import(src('site.ts'));
const { degrees, graduateCoursework, coreFoundations } = await import(src('education.ts'));
const { experience } = await import(src('experience.ts'));
const { projects, research } = await import(src('projects.ts'));
const { skills } = await import(src('skills.ts'));
const { products } = await import(src('shop.ts'));

const out = [];
const w = (s = '') => out.push(s);

w('<!-- GENERATED by bot/build-context.mjs — edit src/data/*.ts, not this file. -->');
w();
w('# Facts from the site');
w();
w(`These are the published facts. The visitor can read them too, so lead with`);
w(`the reasoning in the next section and use these for accuracy, not as a`);
w(`script to recite.`);
w();

w('## Identity');
w();
w(`- Name: ${site.name}`);
w(`- Title: ${site.role}`);
w(`- Site: ${site.url}`);
w(`- Email: ${site.email}`);
w(`- GitHub: ${site.github}`);
w(`- LinkedIn: ${site.linkedin}`);
w();

w('## Education');
w();
for (const d of degrees) w(`- **${d.degree}** — ${d.school} (${d.date})`);
w();
w('Graduate coursework:');
w();
for (const c of graduateCoursework) w(`- ${c.name}: ${c.points.join('; ')}`);
w();
w('Core foundations:');
w();
for (const c of coreFoundations) w(`- ${c.name}: ${c.points.join('; ')}`);
w();

w('## Experience');
w();
for (const r of experience) {
  w(`### ${r.title} — ${r.org}`);
  w(`*${r.date}*`);
  w();
  w(r.blurb);
  w();
}

w('## Research');
w();
for (const p of research) {
  w(`### ${p.title} (${p.years})`);
  w(`Repo: ${p.href} — ${p.tags.join(', ')}`);
  w();
  w(p.blurb);
  w();
}

w('## Projects');
w();
for (const p of projects) {
  w(`### ${p.title} (${p.years})`);
  w(`Repo: ${p.href} — ${p.tags.join(', ')}`);
  w();
  w(p.blurb);
  w();
}

w('## Skills');
w();
for (const g of skills) w(`- **${g.title}:** ${g.items.join(', ')}`);
w();

w('## Shop');
w();
w('Original art and hand-made pieces. Every single one is sold out — that is');
w('the joke and it is not going to change. Listed prices:');
w();
for (const p of products) w(`- ${p.title} — ${p.price}`);
w();

w('## Pages on this site');
w();
for (const n of nav) w(`- ${n.path} — ${n.label}: ${n.description}`);
w();
w('There is also a downloadable resume at /files/Resume.pdf.');
w();

const dest = join(here, 'knowledge', '10-site-facts.md');
writeFileSync(dest, out.join('\n'));
console.log(`bot/build-context: wrote ${dest} (${out.join('\n').length} chars)`);
