#!/usr/bin/env node
/**
 * Regenerates bot/knowledge/10-site-facts.md from src/data/*.ts.
 *
 * The bot's facts and the site's pages come from one source, so adding a role
 * or a project updates both. Node 24 strips the types on import, which is why
 * this can read the .ts modules directly instead of regex-scraping them.
 *
 * Run:  npm run bot:context     (also runs as part of `npm run build`)
 *
 * Do not hand-edit the generated file — put the human context, the parts that
 * are not on the site, in 20-about.md instead.
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = (f) => join(here, '..', 'src', 'data', f);

const { site, nav } = await import(src('site.ts'));
const { degrees, graduateCoursework, coreFoundations } = await import(src('education.ts'));
const { experience } = await import(src('experience.ts'));
const { projects, research } = await import(src('projects.ts'));
const { publications, cite } = await import(src('publications.ts'));
const { skills } = await import(src('skills.ts'));
const { products } = await import(src('shop.ts'));
const { anchors } = await import(src('anchors.ts'));

/* Compact mode. A 4B model handed thousands of tokens of reference material
   deliberates instead of answering — measured: 6,700 chars of reasoning and
   zero chars of reply. This cuts the generated half to what a chat bubble
   actually needs, without touching the hand-written context in 20-about.md. */
const COMPACT = process.env.BOT_COMPACT === 'true';
const clip = (t, n) => (COMPACT && t.length > n ? t.slice(0, t.lastIndexOf(' ', n)) + '…' : t);

const out = [];
const w = (s = '') => out.push(s);

w('<!-- GENERATED by bot/build-context.mjs — edit src/data/*.ts, not this file. -->');
w();
w('# Facts from the site');
w();
w(`These are the published facts. The visitor can read them too, so lead with`);
w(`the reasoning in the next section and use these for accuracy, not as a`);
w(`script to recite.`);
w();

w('## Identity');
w();
w(`- Name: ${site.name}`);
w(`- Title: ${site.role}`);
w(`- Site: ${site.url}`);
w(`- Email: ${site.email}`);
w(`- GitHub: ${site.github}`);
w(`- LinkedIn: ${site.linkedin}`);
w();

/* Hand-maintained, because mapping a role to a domain is judgement, not data.
   It exists because postings ask for "security or defense domain experience"
   and a model reading only job titles concludes he has none — while his record
   is almost entirely defense and security. Stated as fact, it is matched;
   stated as a rule in the JD prompt, it was ignored. */
w('## Domains he has actually worked in');
w();
w('- **Defense / DoD** — AFRL Sensors Directorate, on AFRL/DoD priorities.');
w('- **Cybersecurity** — ransomware detection for Industrial Control Systems,');
w('  presented at IEEE Big Data 2024; the NSF REU was AI-Empowered Cybersecurity.');
w('- **Aerospace** — NASA Missouri Space Grant Consortium.');
w('- **Healthcare** — Geometry Health and Wellness.');
w();
w('A posting asking for security or defense domain experience is asking for');
w('something he has, not something he lacks.');
w();

w('## Education');
w();
for (const d of degrees) w(`- **${d.degree}** — ${d.school} (${d.date})`);
w();
if (COMPACT) {
  w(`Graduate coursework: ${graduateCoursework.map((c) => c.name).join(', ')}.`);
  w(`Core foundations: ${coreFoundations.map((c) => c.name).join(', ')}.`);
} else {
  w('Graduate coursework:');
  w();
  for (const c of graduateCoursework) w(`- ${c.name}: ${c.points.join('; ')}`);
  w();
  w('Core foundations:');
  w();
  for (const c of coreFoundations) w(`- ${c.name}: ${c.points.join('; ')}`);
}
w();

w('## Experience');
w();
for (const r of experience) {
  w(`### ${r.title} — ${r.org}`);
  w(`*${r.date}*`);
  w();
  w(clip(r.blurb, 340));
  w();
}

w('## Publications');
w();
for (const p of publications) {
  w(`### ${p.title} (${p.year})`);
  w(cite(p));
  w(`Tags: ${p.tags.join(', ')}`);
  w();
  w(clip(p.blurb, 340));
  w();
}

w('## Research');
w();
for (const p of research) {
  w(`### ${p.title} (${p.years})`);
  w(p.href ? `Repo: ${p.href} — ${p.tags.join(', ')}` : `Tags: ${p.tags.join(', ')}`);
  w();
  w(clip(p.blurb, 340));
  w();
}

w('## Projects');
w();
for (const p of projects) {
  w(`### ${p.title} (${p.years})`);
  w(p.href ? `Repo: ${p.href} — ${p.tags.join(', ')}` : `Tags: ${p.tags.join(', ')}`);
  w();
  w(clip(p.blurb, 340));
  w();
}

w('## Skills');
w();
for (const g of skills) w(`- **${g.title}:** ${g.items.join(', ')}`);
w();

w('## Shop');
w();
if (COMPACT) {
  w(`Original art, ${products.length} pieces, ${products[0].price}–${products[products.length - 1].price}. Every one sold out — that is the joke.`);
} else {
  w('Original art and hand-made pieces. Every single one is sold out — that is');
  w('the joke and it is not going to change. Listed prices:');
  w();
  for (const p of products) w(`- ${p.title} — ${p.price}`);
}
w();

/* No page list here: the link menu below already names every route, and every
   token in this file is a token the model re-reads on a cold conversation. */

/* ---------------------------------------------------------------------------
 * Link menu.
 *
 * The model may attach a button to an answer, but it must never author a URL —
 * a prompt-injected model that can emit arbitrary hrefs is a phishing-link
 * generator. So it picks a key from this menu instead, and the gateway
 * resolves the key to a href it already knows. Anything unrecognised is
 * dropped.
 *
 * Both halves come from here: links.generated.json for the gateway to check
 * against, and the markdown section below for the model to choose from. One
 * source, so the menu the model sees and the menu the server accepts cannot
 * disagree.
 * ------------------------------------------------------------------------ */
const used = new Set();
const slug = (title) => {
  const words = title.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').split(/\s+/).filter(Boolean);
  let key = words.slice(0, 2).join('-');
  for (let n = 2; used.has(key); n++) key = [...words.slice(0, 2), n].join('-');
  used.add(key);
  return key;
};

const links = [
  ...nav.map((n) => ({ key: n.path, kind: 'route', href: n.path, label: n.label })),
  { key: 'resume-pdf', kind: 'file', href: '/files/Resume.pdf', label: 'Download the resume (PDF)' },
  { key: 'github', kind: 'external', href: site.github, label: 'GitHub profile' },
  { key: 'linkedin', kind: 'external', href: site.linkedin, label: 'LinkedIn' },
  { key: 'email', kind: 'external', href: `mailto:${site.email}`, label: `Email ${site.name.split(' ')[0]}` },
  ...[...research, ...projects]
    .filter((p) => p.href) // coursework has no public repo to offer
    .map((p) => ({
      key: slug(p.title),
      kind: 'external',
      href: p.href,
      label: `${p.title} — repo`,
    })),

  /* Deep links. Slugs come from src/data/anchors.ts, the same module the
     pages use to write their `id=`, so a link the bot offers always lands on
     a card that exists. */
  ...publications.map((p) => ({
    key: slug(p.title),
    kind: 'external',
    href: `https://doi.org/${p.doi}`,
    label: `${p.title} — paper (DOI)`,
  })),

  ...experience.map((r) => ({
    key: `/experience#${anchors.experience.get(r.org)}`,
    kind: 'route',
    href: `/experience#${anchors.experience.get(r.org)}`,
    label: r.org.split(',')[0].trim(),
  })),
  ...publications.map((p) => ({
    key: `/research#${anchors.publications.get(p.title)}`,
    kind: 'route',
    href: `/research#${anchors.publications.get(p.title)}`,
    label: p.title,
  })),
  ...research.map((p) => ({
    key: `/research#${anchors.research.get(p.title)}`,
    kind: 'route',
    href: `/research#${anchors.research.get(p.title)}`,
    label: p.title,
  })),
  ...projects.map((p) => ({
    key: `/projects#${anchors.projects.get(p.title)}`,
    kind: 'route',
    href: `/projects#${anchors.projects.get(p.title)}`,
    label: p.title,
  })),
];

writeFileSync(join(here, 'links.generated.json'), JSON.stringify({ links }, null, 2));

w('## Links you can attach');
w();
w('To put a button under your answer, print `[[LINK]] key` on its own line —');
w('one per line, at most two per reply. Use the key exactly as written here.');
w('Any other value is discarded, so inventing one just loses you the button.');
w();
if (COMPACT) {
  /* One line per link instead of a bulleted block — same information, a third
     of the tokens. */
  w(links.map((l) => `${l.key} = ${l.label}`).join(' | '));
} else {
  for (const l of links) w(`- \`${l.key}\` — ${l.label}`);
}
w();
w('Attach one when it saves the visitor a hunt ("where is the resume?"), not');
w('as decoration on every message.');
w();
w('A key with a `#` in it scrolls to one specific card and flashes it. Prefer');
w('those whenever the question is about a particular role or project — sending');
w('someone to `/experience` when they asked about AFRL makes them hunt through');
w('five entries for the one you meant.');
w();

const dest = join(here, 'knowledge', '10-site-facts.md');
writeFileSync(dest, out.join('\n'));
console.log(
  `bot/build-context: wrote ${dest} (${out.join('\n').length} chars) and links.generated.json (${links.length} links)`,
);
